[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' https://www.youtube.com https://s.ytimg.com https://*.googleapis.com;
    frame-src https://www.youtube.com https://www.youtube-nocookie.com;
    media-src https://*.googlevideo.com;
    connect-src https://*.googleapis.com https://*.googlevideo.com;
    img-src 'self' https://i.ytimg.com data:;
  """
